### PR TITLE
feat: specify utf-8 encoding on exported html

### LINKED ISSUE #134: HTML export: Specify UTF-8 encoding
Herms should put this in the `head` of the HTML documents produced by `herms export --format html`:
```html
<meta charset="UTF-8">
```
The appropriate place to do so is in `Html.htmlDoc`.

### PR DESCRIPTION
**Pull request by aitorres**
This PR adds a meta tag to the HTML layout of exported docs in order to specify UTF-8 as the document's charset, as suggested in issue #134. This is done at the beginning of the `<head>` block, right before any other tags.

Closes #134 (if merged).

Let me know if I missed something or if there's anything else I can help with!

### CODE REVIEW

**Comment by aitorres** [comment]
I'm not sure why I can't reproduce the tests failing on my local environment, I'm getting all tests to pass both in the master branch and on this branch (and what's failing doesn't seem to be related to the introduced change).

Screen Shot 2021-03-27 at 2 13 46 AM

Let me know if there's anything else I can change regarding the PR!

**Comment by langston-barrett** [comment]
Thank you @aitorres! I'll investigate those tests.

**Comment by langston-barrett** [comment]
@aitorres I've fixed the tests, if you rebase this it should pass in CI. Thanks!

**Comment by aitorres** [comment]
Cool! Running tests again now :-)

**Comment by langston-barrett** [comment]
Thank you @aitorres!

**Pull request merged**
